#### Cancer Test Example
Let us apply Bayes' Rule to a Cancer Test Example which is a very common example in Statistic classes.
Suppose, there is a certain type of cancer which is extremely rare.

Let,
\begin{equation}
P(C) = 0.001
\end{equation}
In other words, $1$ in every $1000$ people has this cancer. Can you compute the probability of not having cancer?
\begin{equation}
P(\neg C) = ?
\end{equation}

The test for cancer is not $100\%$ accurate. Let us say, probability of the test being positive given someone has cancer is,
\begin{equation}
P(pos | C) = 0.8
\end{equation}
Can you compute the probability that the test is negative given someone has cancer?
\begin{equation}
P(neg | C) = ?
\end{equation}

Similarly, the probability of a test being positive given that someone has no cancer is $P(pos | \neg C) = 0.1$. Can you compute the probability that the test is negative given someone has no cancer?
\begin{equation}
P(neg | \neg C) = ?
\end{equation}

Can you compute the following?
\begin{equation}
P(C | pos) = ?
\end{equation}
Interpret the quantity you computed in words!

What we computed is very interesting. We computed probability of having cancer given the test results and how likely the disease is.

$P(\neg C) = 1 - P(C) = 0.999$

$P(neg|C) = 1 - P(pos|C) = 0.2$

$P(neg|\neg C) = 0.9$

$P(C|pos) = \frac{0.8 * 0.001}{0.8 * 0001 + 0.999 * 0.1} = 0.007944389275074478$

In [2]:
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('ggplot')

## robot localization

In this exercise we will apply basic concepts of probability and statistics to help a robot localise itself. Robot localization is an important task for any mobile robot as it needs to know where in the world it is currently situated in.

You may think robot localization is a very easy problem as you can use GPS. But no! GPS has errors in localization upto a few metres which is very inaccurate for self driving cars.

Hence, the robot needs to use sensors to locate itself. And sensors are noisy! Even the motion of a robot is uncertain.

For the purposes of this exercise, let us assume that the world is a one dimensional world with $N$ grid cells. Each grid cell is colored either red or green which can be measured using a sensor located in the robot. However, the sensor measurements are noisy and hence we need to take a probabilitic approach to determine in which of these grid cells the robot is situated in at a given instant of time.

The robot can move either left or right in this **cyclic** world. This motion is uncertain as well prompting us again to take a probabilistic approach. For example you may instruct the robot to move $5$ cells. But it may move $4/6$ cells due to a wheel slip.

When the robot is switched on, it is in a state of maximum confusion. It doesn't know where it is situated. We will model this state of maximum confusion as uniform distribution. 
In other words, the robot has equal belief of being present in any of the cells.

Complete the below function to return an array where the $i^{th}$ array element is the probability that the robot is in the $i^{th}$ grid cell at time instant $0$ when the robot is switched on.

In [4]:
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    # Add your code here
    p = np.ones(n)/n
    # End your code here
    return p

In [5]:
init_distribution(5)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [6]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=np.array(['green', 'red', 'red', 'green', 'green'])
p = init_distribution(len(world))
P = np.array([0.25, 0.75])

def sense(p, Z):
    obs = (world == Z).astype("uint8")

    same = np.sum(obs) / len(world)
    diff = 1 - same

    pZx = P[obs]

    _q = pZx * p

    return _q/np.sum(_q)
            
sense(p, 'red'), sense(p, 'green')

(array([0.11111111, 0.33333333, 0.33333333, 0.11111111, 0.11111111]),
 array([0.27272727, 0.09090909, 0.09090909, 0.27272727, 0.27272727]))

In [8]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p=np.array([0.2, 0.2, 0.2, 0.2, 0.2])
world=np.array(['green', 'red', 'red', 'green', 'green'])
measurements = np.array(['red', 'green'])

# Add your code here
for i in measurements:
    p = sense(p, i)
# End your code here
print(p)

[0.2 0.2 0.2 0.2 0.2]


In [9]:
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def move(p, U):
    # ADD CODE HERE
    n = len(p)
    steps = -U % n
    q = [*p, *p]
    # END CODE HERE
    return q[steps:steps+n]

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)

[0.11, 0.11, 0.33, 0.33, 0.11]

In [10]:
def move_p(p, U):
    # probabilistic movement
    P = [(-1, 0.1), (0, 0.8), (1, 0.1)]

    q = np.zeros(len(p)).astype("float32")

    for delta, _p in P:
        q += np.array(move(p, U+delta)) * _p

    return q

move_p(np.float32([0, 1, 0, 0, 0]),1)

array([0. , 0.1, 0.8, 0.1, 0. ], dtype=float32)

In [11]:
p = np.array([0, 1, 0, 0, 0])

for _ in range(1000):
    p = move_p(p, 1)

p

array([0.20000038, 0.20000045, 0.20000038, 0.20000032, 0.20000032],
      dtype=float32)

In [12]:
#Given the list motions=[1,1] which means the robot 
#moves right and then right again, compute the posterior 
#distribution if the robot first senses red, then moves 
#right one, then senses green, then moves right again, 
#starting with a uniform prior distribution.

world=np.array(['green', 'red', 'red', 'green', 'green'])
measurements = ['red', 'green']
motions = [1,1]

p = init_distribution(len(world))
# ADD CODE HERE
for i in range(len(motions)):
    p = sense(p, measurements[i])
    p = move_p(p, motions[i])

p

array([0.21157895, 0.15157893, 0.08105263, 0.16842104, 0.3873684 ],
      dtype=float32)